# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76504be5cafdfcb8080d039a92812922a3c7fc2f1b53e978bf2502a9d496e7ee1e4bb0cbc2705cfa41a72e36d2343249d7b080138a408c75ed4a69b03b1a0b20

test:
  secret_key_base: 656b87533b0c5e3f279b7d35ff0315a0b62930a5ecdcb766f7b904645df078ee80b7b1f789f81710b92e9b5872b248a153bbc42be981f9871df3a43f86e2d8bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
